<?php
/* @var $block \Emertx\BankTransfer\Block\InformPayment */
?>

<style>
    body {
        background: #ffffff;
    }

    #btnMobileCategory,
    #navMobileCategory {
        display: none !important;
    }

    .asterisk {
        top: -5px;
    }

    <?php $ua = strtolower($_SERVER['HTTP_USER_AGENT']); ?>
    <?php if(stripos($ua,'android') !== false): ?>
    input#ebt_slip:after {
        width: 90px;
    }
    <?php endif; ?>

    .uploadEdge {
        width: 100%;
        height: 39px;
        display: none;
        align-items: center;
        cursor: pointer;
    }
    .uploadEdge::after {
        background: #47708c;
        content: "Choose file";
        display: flex;
        width: 90px;
        height: 31px;
        align-items: center;
        position: absolute;
        top: 4.5px;
        justify-content: center;
        color: #fff;
        border-radius: 4px;
    }
    .input-group.baht{
        display: inline-block;
        float: left;
        width: 90%;
    }
    .input-group-addon.baht{
        width: 10%;
        float: left;
        display: inline-block;
        padding: 10px 0px;
    }
</style>

<div class="container" style="margin-top: 65px;">
    <div class="row" id="payment-title">
        <div class="col-md-12 text-sm-center no-padding" style="margin-bottom: 30px">
            <span class="legend-span font-cooper text-xs-size-42">
                <?= __('Payment Form') ?>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 no-padding" id="content">
            <form class="form frm-inform-payment form-horizontal"
                  action="<?php echo $block->getUrl('bank-transfer/pay'); ?>"
                  id="frmInformPayment"
                  method="post"
                  enctype="multipart/form-data"
                  data-hasrequired="<?php echo __('* Required Fields') ?>"
                  data-mage-init='{"validation":{}}'>

                <fieldset class="fieldset fs-transfer">

                    <legend class="secondary-color-1 legend-dgm font-secondary text-bold"><?php echo $block->escapeHtml(__('Transfer Details')); ?></legend>

                    <div class="field form-group bank-account required">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3">
                            <span>
                                <?php echo $block->escapeHtml(__('Bank account')); ?>
                            </span>
                            <span class="asterisk">
                                <i class="fa fa-asterisk" aria-hidden="true"></i>
                            </span>
                        </label>
                        <div class="coltrol col-xs-12 col-md-8 col-lg-9">
                            <?php $bankAccounts = $block->getBankAccounts(); ?>
                            <?php if ($bankAccounts): ?>
                                <table class="tbl-bank-accounts table">
                                    <thead>
                                    <tr>
                                        <th class="text-size-18 text-xs-size-16"></th>
                                        <th class="bank text-size-18 text-xs-size-16"><?php echo $block->escapeHtml(__('Bank')); ?></th>
                                        <th class="bank-accno text-size-18 text-xs-size-16"><?php echo $block->escapeHtml(__('Account No.')); ?></th>
                                        <th class="bank-accname text-size-18 text-xs-size-16"><?php echo $block->escapeHtml(__('Account Name')); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($bankAccounts as $bankAccount): ?>
                                        <tr>
                                            <td>
                                                <div class="radio text-center">
                                                    <input type="radio"
                                                           value="<?php echo $bankAccount->getId(); ?>"
                                                           name="bank_account_id"
                                                           class="dgm-radio"
                                                           id="bank_account_id_<?php echo $bankAccount->getId(); ?>">
                                                    <label for="bank_account_id_<?php echo $bankAccount->getId(); ?>"
                                                           class="radio-label"></label>
                                                </div>
                                            </td>
                                            <td class="bank-name">
                                                <label for="bank_account_id_<?php echo $bankAccount->getId(); ?>">
                                                    <img src="<?php echo $block->getBankLogoUrl($bankAccount->getBank()); ?>"
                                                         class="bank-logo">
                                                    <span class="text-size-18 text-xs-size-16 text-color-1"
                                                          style="font-weight: normal!important;">
                                                    <?php echo $block->escapeHtml($block->getBankName($bankAccount->getBank())); ?>
                                                </span>
                                                </label>
                                            </td>
                                            <td class="bank-accno text-size-18 text-xs-size-16"><?php echo $block->escapeHtml($bankAccount->getAccountNumber()); ?></td>
                                            <td class="bank-accname text-size-18 text-xs-size-16"><?php echo $block->escapeHtml($block->getTranslatedAccountName($bankAccount)); ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="field form-group transfer-date required">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3" for="ebt_date">
                            <span>
                                <?php echo $block->escapeHtml(__('Transfer date')); ?>
                            </span>
                            <span class="asterisk">
                                <i class="fa fa-asterisk" aria-hidden="true"></i>
                            </span>
                        </label>
                        <div class="coltrol col-xs-12 col-md-8 col-lg-9">
                            <input name="date" id="ebt_date"
                                   title="<?php echo $block->escapeHtml(__('Transfer date')); ?>"
                                   value="<?php echo $block->escapeHtml($block->timezone->date()->format('Y-m-d')); ?>"
                                   class="input-text form-control" readonly="readonly" type="text"
                                   data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="field form-group transfer-time required">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3" for="ebt_hour">
                            <span>
                                <?php echo $block->escapeHtml(__('Transfer time')); ?>
                            </span>
                            <span class="asterisk">
                                <i class="fa fa-asterisk" aria-hidden="true"></i>
                            </span>
                        </label>
                        <div class="control col-xs-12 col-md-8 col-lg-9">
                            <select class="input-text form-control" name="hour" id="ebt_hour">
                                <?php for ($i = 0; $i < 24; $i++): ?>
                                    <option value="<?php echo $i; ?>" <?php echo $block->timezone->date()->format('H') == $i ? 'selected' : ''; ?>><?php printf('%02d', $i); ?></option>
                                <?php endfor; ?>
                            </select> :
                            <select class="input-text form-control" name="minute" id="ebt_minute">
                                <?php for ($i = 0; $i < 60; $i++): ?>
                                    <option value="<?php echo $i; ?>" <?php echo $block->timezone->date()->format('i') == $i ? 'selected' : ''; ?>><?php printf('%02d', $i); ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field form-group amount required">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3" for="ebt_amount">
                            <span>
                                <?php echo $block->escapeHtml(__('Amount')); ?>
                            </span>
                            <span class="asterisk">
                                <i class="fa fa-asterisk" aria-hidden="true"></i>
                            </span>
                        </label>
                        <div class="control col-xs-12 col-md-8 col-lg-9">
                            <div class="input-group baht">
                                <input name="amount" id="ebt_amount"
                                       title="<?php echo $block->escapeHtml(__('Amount')); ?>" value=""
                                       class="input-text form-control" type="number"
                                       data-validate="{required:true,'validate-number':true}"/>
                                
                            </div>
                            <div class="input-group-addon baht"><?php echo $block->escapeHtml(__('Baht')); ?></div>
                        </div>
                    </div>
                    <div class="field form-group slip <?php echo $block->isSlipRequired() ? 'required' : ''; ?>">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3" for="ebt_slip">
                            <span>
                                <?php echo $block->escapeHtml(__('Transfer slip')); ?>
                            </span>
                            <span class="asterisk">
                                <i class="fa fa-asterisk" aria-hidden="true"></i>
                            </span>
                        </label>
                        <div class="control col-xs-12 col-md-8 col-lg-9">
                            <div class="form-control uploadEdge">
                                <span id="renderFileNameArea" style="margin-left: 100px;"></span>
                            </div>
                            <input name="slip"
                                   id="ebt_slip"
                                   title="<?php echo $block->escapeHtml(__('Transfer slip')); ?>"
                                   class="input-text form-control <?php if (stripos($_SERVER['HTTP_USER_AGENT'], 'Android')) {
                                       echo 'android';
                                   } ?>"
                                   type="file"
                                   onchange="renderUploadFileName()";
                            />
                            <p>
                                <?php echo $block->escapeHtml(__('Allowed file types: PDF, JPG, GIF, PNG')); ?><br>
                                <?php echo $block->escapeHtml(sprintf(__('Maximum file size: %sMB'), $block->getMaximumFileSize())); ?>
                            </p>
                            <?php
                            $ua = strtolower($_SERVER['HTTP_USER_AGENT']);
                            $lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
                            $acceptLang = ['th', 'en'];
                            $lang = in_array($lang, $acceptLang) ? $lang : 'en';
                            if(stripos($ua, 'iphone') !== false){
                                $iPhone = true;
                            } else {
                                $iPhone = false;
                            }

                            if(stripos($ua, 'ipad') !== false){
                                $iPad = true;
                            } else {
                                $iPad = false;
                            }
                            ?>

                            <p class="hidden">
                                <?= $ua; ?>
                            </p>

                            <?php if (stripos($ua, 'android') !== false): ?>
                                <!-- change placeholder specific browser language-->
                                <?php if ($lang === 'th'): ?>
                                    <style>
                                        input#ebt_slip:after {
                                            content: 'โปรดเลือก';
                                            top: 4px;
                                            left: 27px;
                                            height: 32px;
                                            width: 81px !important;
                                        }
                                    </style>
                                <?php else: ?>
                                    <style>
                                        input#ebt_slip:after {
                                            left: 28px;
                                            width: 100px !important;
                                        }
                                    </style>
                                <?php endif ?>
                            <?php elseif (
                                    stripos($ua, 'mac os') !== false &&
                                    (!$iPhone && !$iPad)
                            ): ?>
                                <style>
                                    input#ebt_slip:after {
                                        width: 92px !important;
                                        height: 25px;
                                        top: 7px;
                                        left: 23px;
                                    }
                                </style>
                            <?php elseif (stripos($ua, 'edge') !== false): ?>
                                <style>
                                    /*display special case input file for microsoft edge*/
                                    .uploadEdge {
                                        display: flex;
                                    }
                                    input#ebt_slip {
                                        position: absolute;
                                        right: 999999999999999px;
                                    }
                                </style>
                            <?php endif; ?>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="fieldset">

                    <legend class="secondary-color-1 legend-dgm font-secondary text-bold"><?php echo $block->escapeHtml(__('Orders')); ?></legend>

                    <div class="field form-group paid-order required">
                        <?php $saleOrders = $block->getUnpaidBankTransferOrders(); ?>
                        <?php if ($saleOrders): ?>
                            <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3">
                            <span>
                                <?php echo $block->escapeHtml(__('Pending orders')); ?>
                            </span>
                            </label>
                            <div class="control col-xs-12 col-md-8 col-lg-9">
                                <table class="tbl-pending-order table">
                                    <thead>
                                    <tr>
                                        <th class="text-size-18 text-xs-size-16"></th>
                                        <th class="ordno text-size-18 text-xs-size-16"><?php echo $block->escapeHtml(__('Order number')); ?></th>
                                        <th class="orddate text-size-18 text-xs-size-16"><?php echo $block->escapeHtml(__('Order date')); ?></th>
                                        <th class="ordtotal text-size-18 text-xs-size-16"><?php echo $block->escapeHtml(__('Order total')); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php /* @var $saleOrder Magento\Sales\Model\Order */ ?>
                                    <?php foreach ($saleOrders as $saleOrder): ?>
                                        <tr>
                                            <td>
                                                <div class="radio text-center">
                                                    <input type="radio"
                                                           value="<?php echo $saleOrder->getId(); ?>"
                                                           name="order_id"
                                                           class="dgm-radio"
                                                           id="order_id_<?php echo $saleOrder->getId(); ?>">
                                                    <label for="order_id_<?php echo $saleOrder->getId(); ?>"
                                                           class="radio-label"></label>
                                                </div>
                                            </td>
                                            <td class="ordno">
                                                <label for="order_id_<?php echo $saleOrder->getId(); ?>">
                                                <span class="text-size-18 text-xs-size-16 text-color-1"
                                                      style="font-weight: normal;">
                                                    <?php echo $block->escapeHtml($saleOrder->getRealOrderId()); ?>
                                                </span>
                                                </label>
                                            </td>
                                            <td class="orddate text-size-18 text-xs-size-16">
                                                <?php /* @escapeNotVerified */
                                                echo $block->formatDate($saleOrder->getCreatedAt(), \IntlDateFormatter::LONG) ?>
                                            </td>
                                            <td class="ordtotal text-size-18 text-xs-size-16">
                                                <?php /* @escapeNotVerified */
                                                echo $saleOrder->formatPrice($saleOrder->getGrandTotal()) ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php else: ?>
                            <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3"
                                   for="ebt_orderno">
                            <span>
                                <?php echo $block->escapeHtml(__('Order number')); ?>
                            </span>
                                <span class="asterisk">
                                <i class="fa fa-asterisk" aria-hidden="true"></i>
                            </span>
                            </label>
                            <div class="control col-xs-12 col-md-8 col-lg-9">
                                <input name="order_number" id="ebt_orderno"
                                       title="<?php echo $block->escapeHtml(__('Order number')); ?>" value=""
                                       class="input-text form-control" type="text" data-validate="{required:true}"/>
                            </div>
                        <?php endif; ?>
                    </div>

                </fieldset>
                <fieldset class="fieldset">
                    <legend class="secondary-color-1 legend-dgm font-secondary text-bold"><?php echo $block->escapeHtml(__('Contact Information')); ?></legend>
                    <div class="field form-group name">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3"
                               for="ebt_name"><span><?php echo $block->escapeHtml(__('Name')); ?></span></label>
                        <div class="control col-xs-12 col-md-8 col-lg-9">
                            <input name="name" id="ebt_name" title="<?php echo $block->escapeHtml(__('Name')); ?>"
                                   value="<?php echo $block->escapeHtml($block->getCustomerName()); ?>"
                                   class="input-text form-control" type="text"/>
                        </div>
                    </div>
                    <div class="field form-group phone">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3"
                               for="ebt_phone"><span><?php echo $block->escapeHtml(__('Phone')); ?></span></label>
                        <div class="control col-xs-12 col-md-8 col-lg-9">
                            <input name="phone" id="ebt_phone" title="<?php echo $block->escapeHtml(__('Phone')); ?>"
                                   value="<?php echo $block->escapeHtml($block->getCustomerPhone()); ?>"
                                   class="input-text form-control" type="tel"/>
                        </div>
                    </div>
                    <div class="field form-group comment">
                        <label class="label label-payment font-secondary col-xs-12 col-md-4 col-lg-3" for="ebt_comment"><span><?php echo $block->escapeHtml(__('Comment')); ?></span></label>
                        <div class="control col-xs-12 col-md-8 col-lg-9">
                            <textarea name="comment" id="ebt_comment"
                                      title="<?php echo $block->escapeHtml(__('Comment')); ?>"
                                      class="input-text form-control" cols="5" rows="3"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar no-padding col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-2">
                    <div class="primary">
                        <button type="button"
                                title="<?php echo $block->escapeHtml(__('Submit')); ?>"
                                class="action submit btn btn-dgm btn-dgm-submit-payment font-secondary">
                            <span><?php echo $block->escapeHtml(__('Submit')); ?></span>
                        </button>
                    </div>
                </div>
            </form>
            <script type="text/x-magento-init">
            {
                "*": {
                    "Emertx_BankTransfer/js/inform": {}
                }
            }

            </script>
            <script>
                require(['jquery'], function ($) {
                    $(document).ready(function () {
                        $('.header-group-icon .btn-group').on('click', function () {
                            if ($(this).hasClass('open')) {
                                $(this).removeClass('open')
                            } else {
                                $(this).addClass('open')
                            }
                        })

                        $('.lg-cart-user .btn-group').on('click', function () {
                            if ($(this).hasClass('open')) {
                                $(this).removeClass('open')
                            } else {
                                $(this).addClass('open')
                            }
                        })

                        $('.uploadEdge').on('click', function () {
                            $('#ebt_slip').click().trigger();
                        })
                    })
                });


                function renderUploadFileName(){
                    var x = document.getElementById("ebt_slip");
                    var renderName = "";
                    if ('files' in x) {
                        if (x.files.length === 0) {
                            renderName = "Select one or more files.";
                        } else {
                            for (var i = 0; i < x.files.length; i++) {
                                var file = x.files[i];
                                if ('name' in file) {
                                    renderName += `${file.name}`;
                                }
                            }
                        }
                    }
                    else {
                        if (x.value === "") {
                            renderName += "Select one or more files.";
                        } else {
                            renderName += "The files property is not supported by your browser!";
                            renderName  += " The path of the selected file: " + x.value; // If the browser does not support the files property, it will return the path of the selected file instead.
                        }
                    }
                    document.getElementById("renderFileNameArea").innerHTML = renderName;
                }
            </script>
        </div>
    </div>
</div>