<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_postDate = $_post->getData("publish_time");
    $share_url = "https://www.facebook.com/sharer/sharer.php?display=popup&u=" . $_post->getPostUrl();
    $options = 'toolbar=0,status=0,resizable=1,width=626,height=436';
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-banner no-banner"></div>
        <!-- <div class="post-date">
            <span class="day"><?//php echo date("j", strtotime($_postDate)); ?></span>
            <span class="month"><?//php echo date("M", strtotime($_postDate)); ?></span>
        </div> -->
        <div class="post-header">
            <!-- <div class="addthis_toolbox addthis_default_style" addthis:url="<?//php echo $_postUrl ?>">
                <a onclick="window.open('<?//php echo $share_url?>', 'sharer','<?//php echo $options?>')">123</a>
            </div> -->
            <?php echo $this->getInfoHtml() ?>
            <h2 class="post-title theme-color detail">
                <?php echo $_postName; ?>
            </h2>
        </div>
        <div class="post-content shortdesc">
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?php echo $block->getShorContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="post-content">
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>

<style>
 .post-view {
    text-align: center;
 }
 .post-view .detail{
 font-family: 'Karla';
     font-weight: 700;
     font-size: 40px;
     text-transform: uppercase;
 }
 .post-categories{
     display: none;
 }
 .post-holder .post-info .item {
    margin-bottom: 3%;
    color: #8b8b8b;
 }
 .post-content{
     margin-top: 6%;
     padding-left: 0;
     padding-right: 0;
     font-size: 20px;
 }
 .onepage-category > .columns{
    padding-right: 0;
 }
 #maincontent.onepage-category {
     padding: 0;
 }
 .post-holder{
     margin-left: 0;
 }
 .gallery-image{
     width: 100%;
 }
 .post-holder {
    margin-left: 0;
    margin-top: 0;
    margin-bottom: 0;
    border: none;
    padding-bottom: 0;
    clear: both;
}
.post-categories{
    display: none;
}
#relate_product {
    margin-top: 25px; 
    padding-right: 6%; 
    padding-left: 6%; 
}
.bg-relate{
    background: url(https://thenext.bearrunrun.com/media/wysiwyg/smartwave/porto/blog/NEWS-BG.png);
    background-size: 100% auto;
    margin-top: 4%;
}
.title_detail{
    font-size: 22px;
    font-family: 'Karla';
    font-weight: 700;
    padding-top: 5%;
    color: #fff;
}
.under_title{
    border-bottom: 1px solid #fff;
    margin-top: 30px;
}
.products{
    margin-top: 4%;
}
.product-item-details{
    margin-left: 15px;
    margin-top: 20px;
}
.product-item-info .product.name a {
    font-size: 16px;
    color: #141515;
}
.product-brand{
    font-size: 12px;
    color: #8b8b8b;
    text-transform: uppercase;  
}
.price-box .price {
    float: left;
    font-family: 'Open Sans', sans-serif;
    font-weight: 400;
    font-size: 13px;
    color: #8b8b8b;
}
.bundle-options-container .block-bundle-summary .product-addto-links > .action, .product-item-actions .actions-secondary.action, .action.tocompare, .product-addto-links .action.tocompare, .moved-add-to-links .action.tocompare, .product-social-links .action.tocompare, .wishlist.split.button > .action.split, .product-social-links .action.mailto.friend, .moved-add-to-links .action.mailto.friend, .product-social-links .action.towishlist, .product-addto-links .action.towishlist, .block-bundle-summary .action.towishlist, .product-item .action.towishlist, .table-comparison .action.towishlist {
    display:none;
}
.post-view .post-bottom {
    margin-top: 0;
}

@media only screen and (max-width: 600px) {
   .post-header {
      margin-top: 10%;
  }
}
</style>
<script type="text/javascript">
    require([
      'jquery',
      'owl.carousel/owl.carousel.min'
    ], function ($) {
      $("#relate_product .owl-carousel").owlCarousel({
        loop: true,
        margin: 0,
        autoplay: true,
        autoplayTimeout: 5000,
        autoplayHoverPause: true,
        navRewind: true,
        nav: false,
        dots: true,
        responsive: {
          0: {
            items:2
          },
          768: {
            items:3
          },
          992: {
            items:4
          },
          1200: {
            items:5
          }
        }
      });
    });
  </script>