<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_postDate = $_post->getData("publish_time");
    $share_url = "https://www.facebook.com/sharer/sharer.php?display=popup&u=" . $_post->getPostUrl();
    $options = 'toolbar=0,status=0,resizable=1,width=626,height=436';
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-banner no-banner"></div>
        <!-- <div class="post-date">
            <span class="day"><?//php echo date("j", strtotime($_postDate)); ?></span>
            <span class="month"><?//php echo date("M", strtotime($_postDate)); ?></span>
        </div> -->
        <div class="post-header">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a onclick="window.open('<?php echo $share_url?>', 'sharer','<?php echo $options?>')">123</a>
            </div>
            <?php echo $this->getInfoHtml() ?>
            <h2 class="post-title theme-color detail">
                <?php echo $_postName; ?>
            </h2>
        </div>
        <div class="post-content">
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?php echo $block->getShorContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="post-content">
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>

<style>
 .post-view {
    text-align: center;
 }
 .post-view .detail{
 font-family: 'Karla';
     font-weight: 700;
     font-size: 40px;
     text-transform: uppercase;
 }
 .post-categories{
     display: none;
 }
 .post-holder .post-info .item {
    margin-bottom: 3%;
    color: #8b8b8b;
 }
 .post-content{
     margin-top: 6%;
     padding-left: 20%;
     padding-right: 20%;
     font-size: 20px;
 }
 .onepage-category > .columns{
    padding-right: 0;
 }
 #maincontent.onepage-category {
     padding: 0;
 }
 .post-holder{
     margin-left: 0;
 }
 .gallery-image{
     width: 100%;
 }
</style>