<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];

    if($_customblock) {
        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="row"><div class="col-md-12">'.$block->toHtml().'</div></div>';
        }
    }



$path = $_SERVER['REQUEST_URI'];
$explode = explode('/', $_SERVER['REQUEST_URI']);
$lang = $explode[1];
$acceptLang = ['th', 'en'];
$lang = in_array($lang, $acceptLang) ? $lang : 'en';
if($lang == 'en') {
    $branches = 'Branches';
}else{
    $branches = 'สาขา';
}

$a_region = [
    [
        'th' => 'กรุงเทพและปริมณฑล',
        'en' => 'Bangkok and vicinity',
        'branches' => [
            [
                'th' => 'เอ็มควอเทียร์',
                'en' => 'Emquartier',
                'tel' => 'Emquartier',
                'url' => 'https://g.page/THENEXTEmQuartier?share',
            ],
            [
                'th' => 'เซ็นทรัลเวิลด์',
                'en' => 'Central World',
                'tel' => '02-063-2742',
                'url' => 'https://g.page/THENEXTCTW?share',
            ],
            [
                'th' => 'พาราไดซ์ พาร์ค',
                'en' => 'Paradise Park',
                'tel' => '02-780-2193',
                'url' => 'https://goo.gl/maps/JjEzJxdSmMNZUTCx5',
            ],
            [
                'th' => 'เซ็นทรัลเวสเกต',
                'en' => 'Central West Gate',
                'tel' => '02-102-7807',
                'url' => 'https://goo.gl/maps/9ubrPs77gkm5iiJd7',
            ],
            [
                'th' => 'เซ็นทรัลอิสต์วิลล์',
                'en' => 'Central Eastville',
                'tel' => '02-102-5219',
                'url' => 'https://goo.gl/maps/oWfW6pdhrVoomVyq5',
            ],
            [
                'th' => 'ซีคอนสแควร์ ศรีนครินทร์',
                'en' => 'Seacon Square Srinakarin',
                'tel' => '02-721-9550',
                'url' => 'https://goo.gl/maps/Zak3Jthm7GrXwNTP9',
            ],
            [
                'th' => 'เซ็นทรัล แจ้งวัฒนะ',
                'en' => 'Central Chaengwattana',
                'tel' => '02-835-3226',
                'url' => 'https://goo.gl/maps/NtMrj8NoH7V5h9XL9',
            ],
            [
                'th' => 'แฟชั่นไอซ์แลนด์',
                'en' => 'Fashion Island',
                'tel' => '02-947-5580',
                'url' => 'https://goo.gl/maps/H87kcS8UxSRNVt5WA',
            ],
            [
                'th' => 'เดอะมอลล์บางแค',
                'en' => 'The Mall Bangkae',
                'tel' => '02-454-9470',
                'url' => 'https://goo.gl/maps/eTUv4MZ4Q2ew52Wx9',
            ],
            [
                'th' => 'เดอะมอลล์บางกะปิ',
                'en' => 'The Mall Bangkapi',
                'tel' => '02-7341747',
                'url' => 'https://goo.gl/maps/Vu43y52byHkCy6C26',
            ],
            [
                'th' => 'เดอะมอลล์บางกะปิ',
                'en' => 'The Mall Bangkapi',
                'tel' => '02-3633017',
                'url' => 'https://goo.gl/maps/xz4F8saTT32Qurw37',
            ],
            [
                'th' => 'เดอะมอลล์งามวงศ์วาน',
                'en' => 'The Mall Ngamwongwan',
                'tel' => '02-029-9753',
                'url' => 'https://goo.gl/maps/YX4e2vXEt4hjLR2m9',
            ],
            [
                'th' => 'สเปล ฟิวเจอร์พาร์ค รังสิต',
                'en' => 'Zpell Future Park Rangsit',
                'tel' => '02-150-9087',
                'url' => 'https://goo.gl/maps/1CySLyKpUsUzfzta6',
            ],
        ],
    ],
    [
        'th' => 'ตะวันตก',
        'en' => 'West',
        'branches' => [
            [
                'th' => 'บลูพอร์ทหัวหิน',
                'en' => 'Bluport Huahin',
                'tel' => '032-908-424',
                'url' => 'https://goo.gl/maps/QpwWhZE2jRgspsVA7',
            ],
            [
                'th' => 'เซ็นทรัลศาลายา',
                'en' => 'Central Salaya',
                'tel' => '034-100-717',
                'url' => 'https://goo.gl/maps/WZyqdjJt69a9KE2x6',
            ],
            [
                'th' => 'เซ็นทรัลมหาชัย',
                'en' => 'Central Mahachai',
                'tel' => '034-491-732',
                'url' => 'https://goo.gl/maps/MifV7tWN6x1ojRVj8',
            ],
            [
                'th' => 'อยุธยาซิตี้พาร์ค',
                'en' => 'Ayutthaya City Park',
                'tel' => '035-950-508',
                'url' => 'https://goo.gl/maps/EcKuH7RvPcu3vRJn6',
            ],
        ],
    ],
    [
        'th' => 'ตะวันออก',
        'en' => 'East',
        'branches' => [
            [
                'th' => 'เทอมินัล 21 พัทยา',
                'en' => 'Terminal 21 Pattaya',
                'tel' => '033-252-377',
                'url' => 'https://goo.gl/maps/QhqsVWeVxTut8gZM9',
            ],
            [
                'th' => 'เซ็นทรัลพัทยาบีช',
                'en' => 'Central Pattaya Beach',
                'tel' => '038-043-376',
                'url' => 'https://g.page/THENEXTCentralPattaya?share',
            ],
            [
                'th' => 'เดอะมอลล์โคราช',
                'en' => 'The Mall Korat',
                'tel' => '044-288-133',
                'url' => 'https://goo.gl/maps/H7Y3RGHkyx2RYSmL9',
            ],
            [
                'th' => 'เดอะมอลล์โคราช',
                'en' => 'The Mall Korat',
                'tel' => '044-393432',
                'url' => 'https://goo.gl/maps/QNJGTdH82Sg57xr97',
            ],
            [
                'th' => 'เทอมินัล 21 โคราช',
                'en' => 'Terminal 21 Korat',
                'tel' => '044-078-300',
                'url' => 'https://goo.gl/maps/8PUhA6LNZb6afbwR9',
            ],
            [
                'th' => 'เซ็นทรัลระยอง',
                'en' => 'Central Rayong',
                'tel' => '033-013-025',
                'url' => 'https://goo.gl/maps/7oFKwkkLSghdxAa77',
            ],
            [
                'th' => 'เซ็นทรัลโคราช',
                'en' => 'Central Korat',
                'tel' => '044-229-419',
                'url' => 'https://goo.gl/maps/au8cRKTe6TVpB6mt7',
            ],
            [
                'th' => 'เซ็นทรัลขอนแก่น',
                'en' => 'Central khon kaen',
                'tel' => '043-288-066',
                'url' => 'https://g.page/THENEXT32?share',
            ],
            [
                'th' => 'เซ็นทรัลอุดรธานี',
                'en' => 'Central Udon Thani',
                'tel' => '042-246-628',
                'url' => 'https://goo.gl/maps/KrWbTnqJEu39zCqz9',
            ],
        ],
    ],
    [
        'th' => 'ใต้',
        'en' => 'South',
        'branches' => [
            [
                'th' => 'เซ็นทรัล ภูเก็ต ฟลอเรสต้า',
                'en' => 'Central Phuket Floresta',
                'tel' => '076-623-800',
                'url' => 'https://goo.gl/maps/9pkS5aq3aatWjK337',
            ],
        ],
    ],
];

?>
<div class="row">
    <div class="col-md-5"><?php echo $this->getChildHtml('contactForm')?></div>
    <div class="col-md-2"></div>
    <div class="col-md-5 d-none d-md-block">
        <img src="<?php echo $block->getBaseUrl(); ?>media/images/the_next_store.jpg" alt=""/>
    </div>
</div>

<div class="row">
<?php foreach($a_region as $region){ ?>
    <div class="col-md-3 contact-info">
        <div class="title-contact-header-<?php echo $lang?>">
            <?php echo $region[$lang];?></b>
        </div>
        <div class="border-title"> </div>
        <?//php echo $_infoblock; ?>
        <div class="row branch_<?php echo $lang?>">
            <?php foreach($region['branches'] as $branch){ ?>
                <div class="col-12 text-left branch-text">
                    <p><?php echo $branch[$lang] ?></p>
                    <p>TEL: <?php echo $branch['tel'] ?></p>
                    <p><a href="<?php echo $branch['url'] ?>" target="_blank"><?php echo $lang == 'th' ? 'ที่ตั้ง' : 'Location' ?></a></p>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>
</div>

<style>
form {
    font-family: 'Prompt';
}
.branch_th, .maps {
    font-family: 'Prompt';
}
.submit_th {
    font-family: 'Prompt'!important;
}
</style>