<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];
    
    if($_customblock) {
        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="row"><div class="col-md-12">'.$block->toHtml().'</div></div>';
        }
    }
?>
<?php
$path = $_SERVER['REQUEST_URI'];
$explode = explode('/', $_SERVER['REQUEST_URI']);
$lang = $explode[1];
$acceptLang = ['th', 'en'];
$lang = in_array($lang, $acceptLang) ? $lang : 'en';
if($lang == 'en') {
    $branches = 'Branches';
}else{
    $branches = 'สาขา';
}
?>
<div class="row">
    <div class="col-md-5"><?php echo $this->getChildHtml('contactForm')?></div>
    <div class="col-md-2"></div>
    <div class="col-md-5 contact-info">
        <div class="title-contact-header-<?php echo $lang?>">
            <?php echo $branches;?></b>
        </div>
        <div class="border-title"> </div>
        <?//php echo $_infoblock; ?>
        <?php if($lang=='en') { ?>
            <div class="row branch-detail branch_en">
                <div class="col-md-12 text-left branch-text">
                    <p>*EmQuartier 4th Floor</p>
                    <p>TEL: 0-2003-6100</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*Central World 4th Floor</p>
                    <p>TEL: 0-2063-2742</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*Terminal 21 2nd Floor</p>
                    <p>TEL: 044-078-300</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Paradise park 1st Floor</p>
                    <p>TEL: 0-2780-2193</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*Central WestGate 2nd Floor</p>
                    <p>TEL: 0-2102-7807</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*Central EastVille 2nd Floor</p>
                    <p>TEL: 0-2102-5219</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*Seacon Square 2nd Floor</p>
                    <p>TEL: 0-2721-9550</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*The Mall Thapra 2nd Floor</p>
                    <p>TEL: 0-2477-9240</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Chaengwattana 4th Floor</p>
                    <p>TEL: 0-2835-3226</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Fashion Island 2nd Floor</p>
                    <p>TEL: 0-2947-5580</p>
                </div>

                    <div class="col-md-12 text-left branch-text">
                    <p>*The Mall Bangkhae 1st Floor</p>
                    <p>TEL: 0-2454-9470</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*The Mall Bangkapi 2nd Floor</p>
                    <p>TEL: 0-2363-3017</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*The Mall Ngamwongwan 2nd Floor</p>
                    <p>TEL: 0-2029-9753</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Zpell 1st Floor</p>
                    <p>TEL: 0-2150-9087</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Saphan Mai</p>
                    <p>TEL: 0-2521-1684</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Blu'port (Huahin) G Floor</p>
                    <p>TEL: 032-908-424</p>
                </div>

                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Salaya 3rd Floor</p>
                    <p>TEL: 034-100-717</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*CentralPlaza Mahachai 2nd Floor</p>
                    <p>TEL: 034-491-732</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Robinson Chachoengsao 2nd Floor</p>
                    <p>TEL: 038-564-259</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*The Mall Korat 1st Floor</p>
                    <p>TEL: 044-393-432</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*The Mall Korat 2nd Floor</p>
                    <p>TEL: 044-288-133</p>
                </div>

                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Rayong 2nd Floor</p>
                    <p>TEL: 033-013-025</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Phuket 3rd Floor</p>
                    <p>TEL: 076-623-800</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Terminal pattaya 1st Floor</p>
                    <p>TEL: 033-252-377</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Pattaya beach 4th Floor</p>
                    <p>TEL: 038-043-376</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Ayutthaya City Park 1st Floor</p>
                    <p>TEL: 035-950-508</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Nakorn Rachasima 3rd Floor</p>
                    <p>TEL: 044-229-419</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Central KhonKaen 3rd Floor</p>
                    <p>TEL: 043-288-066</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*Central Udonthani 2nd Floor</p>
                    <p>TEL: 042-246-628</p>
                </div>
                </div>

        <?php }else{ ?>
            <div class="row branch-detail branch_th">
                <div class="col-md-12 text-left branch-text">
                    <p>*เอ็มควอเทียร์ ชั้น 4</p>
                    <p>TEL: 0-2003-6100</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัลเวิลด์ ชั้น 4</p>
                    <p>TEL: 0-2063-2742</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*เทอร์มินอล 21 ชั้น 2</p>
                    <p>TEL: 044-078-300</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*พาราไดซ์ พาร์ค ชั้น 1</p>
                    <p>TEL: 0-2780-2193</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล เวสต์เกต ชั้น 2</p>
                    <p>TEL: 0-2102-7807</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล อีสต์วิลล์ ชั้น 2</p>
                    <p>TEL: 0-2102-5219</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*ซีคอนสแควร์ ศรีนครินทร์ ชั้น 2</p>
                    <p>TEL: 0-2721-9550</p>
                </div>
                <div class="col-md-12 text-left branch-text">
                    <p>*เดอะมอลล์ ท่าพระ ชั้น 2</p>
                    <p>TEL: 0-2477-9240</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล แจ้งวัฒนะ ชั้น 4</p>
                    <p>TEL: 0-2835-3226</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*แฟชั่นไอส์แลนด์ ชั้น 2</p>
                    <p>TEL: 0-2947-5580</p>
                </div>

                    <div class="col-md-12 text-left branch-text">
                    <p>*เดอะมอลล์ บางแค ชั้น 1</p>
                    <p>TEL: 0-2454-9470</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เดอะมอลล์ บางกะปิ ชั้น 2</p>
                    <p>TEL: 0-2363-3017</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เดอะมอลล์ งามวงศ์วาน ชั้น 2</p>
                    <p>TEL: 0-2029-9753</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*สเปลล์ ชั้น 1</p>
                    <p>TEL: 0-2150-9087</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*สะพานใหม่</p>
                    <p>TEL: 0-2521-1684</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*บลูพอร์ต หัวหิน ชั้น G</p>
                    <p>TEL: 032-908-424</p>
                </div>

                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล ศาลายา ชั้น 3</p>
                    <p>TEL: 034-100-717</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล มหาชัย ชั้น 2</p>
                    <p>TEL: 034-491-732</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*โรบินสัน ฉะเชิงเทรา ชั้น 2</p>
                    <p>TEL: 038-564-259</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เดอะมอลล์ โคราช ชั้น 1</p>
                    <p>TEL: 044-393-432</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เดอะมอลล์ โคราช ชั้น 2</p>
                    <p>TEL: 044-288-133</p>
                </div>

                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล ระยอง ชั้น 2</p>
                    <p>TEL: 033-013-025</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล ภูเก็ต ชั้น 3</p>
                    <p>TEL: 076-623-800</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เทอร์มินอล พัทยา ชั้น 1</p>
                    <p>TEL: 033-252-377</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล พัทยา บีช ชั้น 4</p>
                    <p>TEL: 038-043-376</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*อยุธยาซิตี้พาร์ค ชั้น 1</p>
                    <p>TEL: 035-950-508</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล นครราชสีมา ชั้น 3</p>
                    <p>TEL: 044-229-419</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล ขอนแก่น ชั้น 3</p>
                    <p>TEL: 043-288-066</p>
                </div>
                    <div class="col-md-12 text-left branch-text">
                    <p>*เซ็นทรัล อุดรธานี ชั้น 2</p>
                    <p>TEL: 042-246-628</p>
                </div>
                </div>

        <?php } ?>
    </div>
</div>
<div class="row maps">
   <p class="col-md-12 text-center">
        บริษัท แว่นตา เอ แอนด์ พี จำกัด <br>
        328 ถนน พหลโยธิน แขวงอนุสาวรีย์ เขตบางเขน  <br>
        กรุงเทพมหานคร 10220 <br>
        โทรศัพท์ : (02)970-3714-16  <br>
        แฟกซ์ : (02)970-3717-18  <br>
        อีเมล : anpoptical@yahoo.com  <br>
   </p>
   <br>
   <div id="img-maps" onclick='window.open("https://www.google.co.th/maps/search/the+next+%E0%B9%81%E0%B8%A7%E0%B9%88%E0%B8%99%E0%B8%95%E0%B8%B2%2F%E0%B8%95%E0%B8%B1%E0%B8%94%E0%B9%81%E0%B8%A7%E0%B9%88%E0%B8%99/@13.6968458,100.5082644,11z");'></div>
</div> 

<style>
form {
    font-family: 'Prompt';
}
.branch_th, .maps {
    font-family: 'Prompt';
}
.submit_th {
    font-family: 'Prompt'!important;
}
</style>