<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];
    
    if($_customblock) {
        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="row"><div class="col-md-12">'.$block->toHtml().'</div></div>';
        }
    }
?>
<?php
$lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
$acceptLang = ['th', 'en'];
$lang = in_array($lang, $acceptLang) ? $lang : 'en';
?>
<?php echo $lang;?>
<div class="row">
    <div class="col-md-5"><?php echo $this->getChildHtml('contactForm')?></div>
    <div class="col-md-2"></div>
    <div class="col-md-5 contact-info">
        <div class="contacts-title"><?php echo __('Contact') ?> <b><?php echo __('Details') ?></b></div>
        <?php echo $_infoblock; ?>
    </div>
</div>