<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$path = $_SERVER['REQUEST_URI'];
$explode = explode('/', $_SERVER['REQUEST_URI']);
$lang = $explode[1];
$acceptLang = ['th', 'en'];
$lang = in_array($lang, $acceptLang) ? $lang : 'en';
if($lang == 'en') {
    $title = 'Appointment';
}else{
    $title = 'นัดหมายพบแพทย์';
}
?>
<form class="form contact"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <span class="title-contact-header-<?php echo $lang?>"><?php echo $title;?></b></span>
            <div class="border-title"> </div>
        </legend>
        <br />
        <fieldset class="fieldset row">
            <div class="fields col-md-12">
                <div class="field name required">
                    <label class="label col-md-3" for="name"><span><?php echo __('Name') ?></span></label>
                    <div class="control col-md-9">
                        <input name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field telephone required">
                    <label class="label col-md-3" for="telephone"><span><?php echo __('Phone') ?></span></label>
                    <div class="control col-md-9">
                        <input name="telephone" id="telephone" title="<?php echo __('Phone') ?>" value="" class="input-text" type="text" data-validate="{required:true}" />
                    </div>
                </div>
                <div class="field email required">
                    <label class="label col-md-3" for="email"><span><?php echo __('Email') ?></span></label>
                    <div class="control col-md-9">
                        <input name="email" id="email" title="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field datebook required">
                    <label class="label col-md-3" for="datebook"><span><?php echo __('Date Time') ?></span></label>
                    <div class="control col-md-9">
                        <input name="datebook" id="datebook" title="<?php echo __('Date Time') ?>" value="" class="input-text" type="text" data-validate="{required:true, 'validate-date':true}" />
                        <script> require(["jquery", "mage/calendar"], 
                            function($){ 
                                $('#datebook').datetimepicker({
                                        stepMinute: 15,
                                        minDate: new Date(),
                                        dateFormat:'yy-mm-dd',
                                        beforeShowDay: $.datepicker.noWeekends,
                                        hourMin: 6,
                                        hourMax: 16
                                    }
                                );
                            }); 
                        </script>
                    </div>
                </div>
                <div class="field branch">
                    <label class="label col-md-3" for="branch"><span><?php echo __('branch') ?></span></label>
                    <div class="control col-md-9">
                       <select name='branch' class="form-control">
                            <option value="">Please select Branch</option>
                            <option value="AYUTTHAYA CITY PARK">AYUTTHAYA CITY PARK</option>
                            <option value="BLUE PORT HUA HIN">BLUE PORT HUA HIN</option>
                            <option value="CENTRAL CHAENGWATTANA">CENTRAL CHAENGWATTANA</option>
                            <option value="CENTRAL EASTVILLE">CENTRAL EASTVILLE</option>
                            <option value="CENTRAL FESTIVAL PATTAYA BEACH">CENTRAL FESTIVAL PATTAYA BEACH</option>
                            <option value="CENTRAL FESTIVAL PHUKET">CENTRAL FESTIVAL PHUKET</option>
                            <option value="CENTRAL FESTIVAL SAMUI">CENTRAL FESTIVAL SAMUI</option>
                            <option value="CENTRAL KHONKAEN">CENTRAL KHONKAEN</option>
                            <option value="CENTRAL LADPRAO">CENTRAL LADPRAO</option>
                            <option value="CENTRAL MAHACHAI">CENTRAL MAHACHAI</option>
                            <option value="CENTRAL NAKHON RATCHASIMA">CENTRAL NAKHON RATCHASIMA</option>
                            <option value="CENTRAL PINKLAO">CENTRAL PINKLAO</option>
                            <option value="CENTRAL RAYONG">CENTRAL RAYONG</option>
                            <option value="CENTRAL SALAYA">CENTRAL SALAYA</option>
                            <option value="CENTRAL UDONTHANI">CENTRAL UDONTHANI</option>
                            <option value="CENTRAL WORLD">CENTRAL WORLD</option>
                            <option value="CENTRAL WESTGATE">CENTRAL WESTGATE</option>
                            
                            <option value="EMQUARTIER">EMQUARTIER</option>
                            <option value="FASHION ISLAND">FASHION ISLAND</option>
                            <option value="PARADISE PARK">PARADISE PARK</option>
                            <option value="ROBINSON CHACHOENGSAO">ROBINSON CHACHOENGSAO</option>
                            <option value="SEACON SQUARE">SEACON SQUARE</option>
                            <option value="THE MALL BANGKAPI">THE MALL BANGKAPI</option>
                            <option value="THE MALL BANGKAE">THE MALL BANGKAE</option>
                            <option value="THE MALL NGAMWINGWAN">THE MALL NGAMWINGWAN</option>
                            <option value="THE MALL THA PHRA">THE MALL THA PHRA</option>
                            <option value="THE MALL KORAT">THE MALL KORAT</option>
                            <option value="TERMINAL21 KORAT">TERMINAL21 KORAT</option>
                            <option value="TERMINAL21 PATTAYA">TERMINAL21 PATTAYA</option>
                            <option value="ZPELL">ZPELL</option>
                           
                           
                       </select>
                        <!-- <input name="branch" id="branch" title="<?php echo __('branch') ?>" value="" class="input-text" type="text" data-validate="{required:true}" /> -->
                    </div>
                </div>
                <div class="field problem">
                    <label class="label col-md-3" for="problem"><span><?php echo __('Problem') ?></span></label>
                    <div class="control col-md-9">
                        <input name="problem" id="problem" title="<?php echo __('Problem') ?>" value="" class="input-text" type="text"/>
                    </div>
                </div>
                <div class="field comment">
                    <label class="label col-md-3" for="note"><span><?php echo __('Note') ?></span></label>
                    <div class="control col-md-9">
                        <input name="note" id="note" title="<?php echo __('Note') ?>" value="" class="input-text" type="text"/>
                    </div>
                </div>
            </div>
            <div class="fields col-md-12">
                <!-- <div class="field comment required">
                    <label class="label col-md-3" for="comment"><span><?php echo __('Note') ?></span></label>
                    <div class="control col-md-9" style="margin-top: 3%;">
                        <textarea name="comment" id="comment" title="<?php echo __('Note') ?>" class="input-text" cols="5" rows="1" data-validate="{required:true}"></textarea>
                    </div>
                </div> -->
                <?php echo $block->getChildHtml('form.additional.info'); ?>
            </div>
        </fieldset>
    </fieldset>
    <div class="actions-toolbar row">
        <div class="col-md-5 notice">
            <span class="error-notice">*</span> Required
        </div>
        <div class="primary col-md-7 button-contact">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary submit-contact">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
