<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$path = $_SERVER['REQUEST_URI'];
$explode = explode('/', $_SERVER['REQUEST_URI']);
$lang = $explode[1];
$acceptLang = ['th', 'en'];
$lang = in_array($lang, $acceptLang) ? $lang : 'en';
if($lang == 'en') {
    $title = 'Appointment';
}else{
    $title = 'นัดหมายพบแพทย์';
}
?>
<form class="form contact"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <span class="title-contact-header-<?php echo $lang?>"><?php echo $title;?></b></span>
            <div class="border-title"> </div>
        </legend>
        <br />
        <fieldset class="fieldset row">
            <div class="fields col-md-12">
        <div class="field name required">
            <label class="label col-md-3" for="name"><span><?php echo __('Name') ?></span></label>
            <div class="control col-md-9">
                <input name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label col-md-3" for="email"><span><?php echo __('Email') ?></span></label>
            <div class="control col-md-9">
                <input name="email" id="email" title="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label col-md-3" for="telephone"><span><?php echo __('Phone') ?></span></label>
            <div class="control col-md-9">
                <input name="telephone" id="telephone" title="<?php echo __('Phone') ?>" value="" class="input-text" type="text" />
            </div>
        </div>
            </div>
            <div class="fields col-md-12">
        <div class="field comment required">
            <label class="label col-md-3" for="comment"><span><?php echo __('Note') ?></span></label>
            <div class="control col-md-9">
                <textarea name="comment" id="comment" title="<?php echo __('Note') ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
            </div>
        </fieldset>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
